---
title: "Heidi_ExploringTrends"
author: "Heidi Erfourth and Zoe Schroder"
date: "2023-07-25"
output: html_document
---

“Exploring trends in tornado outbreak environments and greenhouse gas concentrations” 

`Pursue publication:` International Journal of Climatology
                      https://mc.manuscriptcentral.com/joc 

**Make sure to follow the Author Resources for publication in the Journal. This includes page formatting, section headers, figure format, table format, figure/table location in manuscript, etc.**

```{r}
install.packages("dplyr")
install.packages("ggplot2")
```

```{r}
library("dplyr")
library("ggplot2")
```

```{r}
AnnGHG <- read.csv("AnnualAverages_GHG.csv")
dim(AnnGHG)

# grouping CO2_ppm and creating chart

str(AnnGHG)

AnnGHG%>%
  group_by(year)%>%
  select("CO2_ppm")
  
ggplot(AnnGHG, aes(x=year, y=CO2_ppm))+
  geom_bar(stat="identity", fill="orange", width=0.9)+
  geom_smooth(color="black",linewidth=1.5)+
  theme_bw()+
  xlab("Years Recorded")+
  ylab("CO2 Concenration (ppm)")+
  scale_x_continuous(expand=c(0,0), limits=c(1960,2030), breaks=c(1960, 1970, 1980, 1990, 2000, 2010, 2020, 2030))+
  scale_y_continuous(expand=c(0,0), limits=c(200,500), breaks=c(200, 225, 250, 275, 300, 325, 350, 375, 400, 425, 450, 475, 500))

  
ggplot(AnnGHG, aes(x=year, y=CH4_ppb))+
    geom_bar(stat="identity", fill="pink", width=0.9)+
    geom_smooth(color="black", linewidth=1.5)+
    xlab("Years Recorded")+
    ylab("CH4 (ppb)")+
    scale_x_continuous(limits=c(1980,2029), breaks=c(1980, 1970, 1980, 1990, 2000, 2010, 2020, 2030))+
    scale_y_continuous(limits=c(1600,2000), breaks=c(1600, 1650, 1700, 1750, 1800, 1850, 1900, 1950, 2000))

ggplot(AnnGHG, aes(x=year, y=N20_ppb))+
  geom_bar(stat="identity", fill="green", width=0.9)+
  geom_smooth(color="black", linewidth=1.5)

ggplot(AnnGHG, aes(x=year, y=SF6_ppt))+
  geom_bar(stat="identity", fill="purple", width=0.9)+
  geom_smooth(color="black", linewidth=1.5)

ggplot(AnnGHG, aes(x=year, y=O3_DU))+
  geom_bar(stat="identity", fill="red", width=0.9)+
  geom_smooth(color="black", linewidth=1.5)

ggplot(AnnGHG, aes(x=year, y=AGGI))+
  geom_bar(stat="identity", fill="blue", width=0.9)+
  geom_smooth(color="black", linewidth=1.5)


```

 